### ISSUE TITLE
UE5.3.2にて導入エラーが出る

### ISSUE THREAD

**Issue by masada-tea** [HANON-games/Shiden#5]
UE5.3.2を使用しています。
新しくブランクプロジェクトを作成してプラグインを導入してみたのですが、

LogEditorUtilityBlueprint: Error: Found Invalid Blueprint in FindUtilityWidgetFromBlueprint

というエラーが出てエディタウインドウが開けません。
新規プロジェクトで始める際にブランクではない方がよかったでしょうか？

**Comment by HANON-games** [comment]
@masada-tea 
Shiden をダウンロードいただきありがとうございます！
手元の UE 5.3.2 にて検証したのですが、5.4.3 をベースにしたプロジェクトを 5.3.2 向けにビルドした関係で 5.3.2 では正常に動作しないことが判明しました。
そのため大変お手数をおかけしますが、UE 5.4.3 にてお試しいただけますと幸いです。

次回のベータ版アップデートの際に UE 5.3.2 向けの対応を試してみますが、次回のアップデートが比較的規模の大きいものになりますので、対応が難しければ対象バージョンを 5.4 以降とさせていただくかもしれません。

ご迷惑をおかけしますが以上よろしくお願いいたします。

**Comment by masada-tea** [comment]
ありがとうございます、5.4.3で試してみたところ正常に動作しました。

**Comment by HANON-games** [comment]
正常に動作したとのことで良かったです。
こちら一旦クローズさせていただきます。
